from __future__ import annotations


SUPPORTED_LANGUAGES = {
    "ru": "Русский",
    "uk": "Українська",
    "en": "English",
}


TEXT = {
    "ru": {
        "owner": "Владелец организации",
        "overview": "Обзор",
        "employees": "Сотрудники",
        "roles": "Роли",
        "permissions": "Права",
        "providers": "ИИ и CLI",
        "audit": "Журнал действий",
        "all": "Все",
        "all_roles": "Все роли",
        "all_providers": "Все provider",
        "workspace": "Рабочая папка",
        "warnings_only": "Только предупреждения",
        "name": "Имя",
        "agent_id": "ID сотрудника",
        "status": "Статус",
        "provider": "Провайдер",
        "findings": "Замечания",
        "organization_owner": "Владелец организации",
        "management_repository": "Служебное хранилище",
        "providers_available": "Провайдеры доступны",
        "providers_unavailable": "Провайдеры недоступны",
        "delete_permanently": "Удалить навсегда",
        "persona": "Профиль общения",
        "rights": "Права",
        "readiness": "Готовность",
        "add_employee": "Добавить сотрудника",
        "open": "Открыть",
        "edit": "Редактировать",
        "suspend": "Приостановить",
        "reactivate": "Вернуть в работу",
        "archive": "Архивировать",
        "employee_card": "Карточка сотрудника",
        "basic_data": "Основные данные",
        "description": "Описание",
        "avatar": "Аватар",
        "generate_id": "Сгенерировать ID",
        "generate_personality": "Сгенерировать личность",
        "generate_personality_hint": "Заполнить имя, пол, биографию и аватар одной кнопкой. Поля можно изменить вручную.",
        "gender": "Пол",
        "role": "Роль",
        "select_roles": "Выберите одну или несколько ролей",
        "inherited_permissions": "Права от роли",
        "provider_status": "Состояние провайдера",
        "review": "Проверка",
        "review_config": "Проверьте конфигурацию перед созданием.",
        "dry_run": "Проверить без сохранения",
        "create_employee": "Создать сотрудника",
        "cancel": "Отмена",
        "no_warnings": "Предупреждений нет.",
        "not_set": "Не задано",
        "not_checked": "Не проверено",
        "reason": "Укажите причину:",
        "cannot_create": "Нельзя создать",
        "check": "Проверка",
        "ok": "OK",
        "rejected": "Отклонено",
        "database_rows": "Записи в базе",
        "files": "Файлы",
        "warnings": "Предупреждения",
        "errors": "Ошибки",
        "no": "нет",
        "provider_page_note": "ИИ и CLI: установка, авторизация, доступ и готовность проверяются раздельно. Установка и логин сейчас не запускаются автоматически.",
        "repeat_check": "Повторить проверку",
        "diagnostics": "Диагностика",
        "roles_readonly": "Создание и редактирование ролей будет в следующем этапе. Сейчас роли доступны для просмотра и назначения.",
        "responsibilities": "Задачи роли",
        "restrictions": "Ограничения",
        "direct_grants": "Дополнительные права",
        "direct_denies": "Запрещенные права",
        "effective_permissions": "Итоговые права",
        "identity": "Карточка",
        "organization": "Организация",
        "professions": "Профессии",
        "skills": "Навыки",
        "learning": "Обучение",
        "templates": "Шаблоны",
        "settings": "Настройки",
        "configuration_health": "Состояние настройки",
        "execution_eligibility": "Готовность к работе",
        "employee": "Сотрудник",
        "provider_id": "ID провайдера",
        "display_name": "Отображаемое имя",
        "family": "Семейство",
        "adapter": "Адаптер",
        "executables": "Команды запуска",
        "install_strategy": "Установка",
        "auth_strategy": "Авторизация",
        "required_capabilities": "Нужные возможности",
        "limitations": "Ограничения",
        "last_health": "Последняя проверка",
        "install": "Установка",
        "auth": "Авторизация",
        "access": "Доступ",
        "health": "Состояние",
        "capabilities": "Возможности",
        "version": "Версия",
        "action": "Действие",
        "object_type": "Тип объекта",
        "object_id": "ID объекта",
        "previous": "Было",
        "new": "Стало",
        "time": "Время",
        "actor": "Кто изменил",
        "filter_audit": "Фильтр по действию, объекту или сотруднику",
        "not_saved": "Не сохранено",
        "check_data": "Проверьте данные",
        "name_required": "Имя сотрудника обязательно.",
        "agent_id_required": "ID сотрудника должен начинаться с agent-.",
        "role_required": "Выберите хотя бы одну роль.",
        "permissions_note": "Дополнительные права. Права владельца через это окно не назначаются.",
        "change_reason": "Причина изменения:",
        "foreign_key_error": "Не удалось сохранить: выбранная роль или провайдер не зарегистрированы. Обновите окно и попробуйте снова.",
        "unknown_role": "Неизвестная роль",
        "unknown_provider": "Неизвестный провайдер",
        "unknown_agent": "Сотрудник не найден",
        "empty_display_name": "Имя сотрудника не заполнено",
    },
    "uk": {
        "owner": "Власник організації",
        "overview": "Огляд",
        "employees": "Працівники",
        "roles": "Ролі",
        "permissions": "Права",
        "providers": "ШІ та CLI",
        "audit": "Журнал дій",
        "all": "Усі",
        "all_roles": "Усі ролі",
        "all_providers": "Усі провайдери",
        "workspace": "Робоча папка",
        "warnings_only": "Лише попередження",
        "name": "Ім'я",
        "agent_id": "ID співробітника",
        "status": "Стан",
        "provider": "Провайдер",
        "findings": "Зауваження",
        "organization_owner": "Власник організації",
        "management_repository": "Службове сховище",
        "providers_available": "Провайдери доступні",
        "providers_unavailable": "Провайдери недоступні",
        "delete_permanently": "Видалити назавжди",
        "persona": "Профіль спілкування",
        "rights": "Права",
        "readiness": "Готовність",
        "add_employee": "Додати співробітника",
        "open": "Відкрити",
        "edit": "Редагувати",
        "suspend": "Призупинити",
        "reactivate": "Повернути в роботу",
        "archive": "Архівувати",
        "employee_card": "Картка співробітника",
        "basic_data": "Основні дані",
        "description": "Опис",
        "avatar": "Аватар",
        "generate_id": "Згенерувати ID",
        "generate_personality": "Згенерувати особистість",
        "generate_personality_hint": "Заповнити ім'я, стать, біографію та аватар однією кнопкою. Поля можна змінити вручну.",
        "gender": "Стать",
        "role": "Роль",
        "select_roles": "Оберіть одну або кілька ролей",
        "inherited_permissions": "Права від ролі",
        "provider_status": "Стан провайдера",
        "review": "Перевірка",
        "review_config": "Перевірте конфігурацію перед створенням.",
        "dry_run": "Перевірити без збереження",
        "create_employee": "Створити співробітника",
        "cancel": "Скасувати",
        "no_warnings": "Попереджень немає.",
        "not_set": "Не задано",
        "not_checked": "Не перевірено",
        "reason": "Вкажіть причину:",
        "cannot_create": "Не можна створити",
        "check": "Перевірка",
        "ok": "OK",
        "rejected": "Відхилено",
        "database_rows": "Записи в базі",
        "files": "Файли",
        "warnings": "Попередження",
        "errors": "Помилки",
        "no": "ні",
        "provider_page_note": "ШІ та CLI: встановлення, авторизація, доступ і готовність перевіряються окремо. Встановлення і логін зараз не запускаються автоматично.",
        "repeat_check": "Повторити перевірку",
        "diagnostics": "Діагностика",
        "roles_readonly": "Створення і редагування ролей буде в наступному етапі. Зараз ролі доступні для перегляду і призначення.",
        "responsibilities": "Завдання ролі",
        "restrictions": "Обмеження",
        "direct_grants": "Додаткові права",
        "direct_denies": "Заборонені права",
        "effective_permissions": "Підсумкові права",
        "identity": "Картка",
        "organization": "Організація",
        "professions": "Професії",
        "skills": "Навички",
        "learning": "Навчання",
        "templates": "Шаблони",
        "settings": "Налаштування",
        "configuration_health": "Стан налаштування",
        "execution_eligibility": "Готовність до роботи",
        "employee": "Співробітник",
        "provider_id": "ID провайдера",
        "display_name": "Відображуване ім'я",
        "family": "Сімейство",
        "adapter": "Адаптер",
        "executables": "Команди запуску",
        "install_strategy": "Встановлення",
        "auth_strategy": "Авторизація",
        "required_capabilities": "Потрібні можливості",
        "limitations": "Обмеження",
        "last_health": "Остання перевірка",
        "install": "Встановлення",
        "auth": "Авторизація",
        "access": "Доступ",
        "health": "Стан",
        "capabilities": "Можливості",
        "version": "Версія",
        "action": "Дія",
        "object_type": "Тип об'єкта",
        "object_id": "ID об'єкта",
        "previous": "Було",
        "new": "Стало",
        "time": "Час",
        "actor": "Хто змінив",
        "filter_audit": "Фільтр за дією, об'єктом або співробітником",
        "not_saved": "Не збережено",
        "check_data": "Перевірте дані",
        "name_required": "Ім'я співробітника обов'язкове.",
        "agent_id_required": "ID співробітника має починатися з agent-.",
        "role_required": "Оберіть хоча б одну роль.",
        "permissions_note": "Додаткові права. Права власника через це вікно не призначаються.",
        "change_reason": "Причина зміни:",
        "foreign_key_error": "Не вдалося зберегти: вибрана роль або провайдер не зареєстровані. Оновіть вікно і спробуйте знову.",
        "unknown_role": "Невідома роль",
        "unknown_provider": "Невідомий провайдер",
        "unknown_agent": "Співробітника не знайдено",
        "empty_display_name": "Ім'я співробітника не заповнене",
    },
    "en": {
        "owner": "Organization owner",
        "overview": "Overview",
        "employees": "Employees",
        "roles": "Roles",
        "permissions": "Permissions",
        "providers": "AI and CLI",
        "audit": "Audit log",
        "all": "All",
        "all_roles": "All roles",
        "all_providers": "All providers",
        "workspace": "Workspace folder",
        "warnings_only": "Warnings only",
        "name": "Name",
        "agent_id": "Employee ID",
        "status": "Status",
        "provider": "Provider",
        "findings": "Findings",
        "organization_owner": "Organization owner",
        "management_repository": "Management storage",
        "providers_available": "Providers available",
        "providers_unavailable": "Providers unavailable",
        "delete_permanently": "Delete permanently",
        "persona": "Persona",
        "rights": "Permissions",
        "readiness": "Readiness",
        "add_employee": "Add employee",
        "open": "Open",
        "edit": "Edit",
        "suspend": "Suspend",
        "reactivate": "Reactivate",
        "archive": "Archive",
        "employee_card": "Employee profile",
        "basic_data": "Basic data",
        "description": "Description",
        "avatar": "Avatar",
        "generate_id": "Generate ID",
        "generate_personality": "Generate personality",
        "generate_personality_hint": "Fill in name, gender, biography and avatar with one click. Fields remain editable.",
        "gender": "Gender",
        "role": "Role",
        "select_roles": "Select one or more roles",
        "inherited_permissions": "Inherited permissions",
        "provider_status": "Provider status",
        "review": "Review",
        "review_config": "Review configuration before creation.",
        "dry_run": "Validate without saving",
        "create_employee": "Create employee",
        "cancel": "Cancel",
        "no_warnings": "No warnings.",
        "not_set": "Not set",
        "not_checked": "Not checked",
        "reason": "Enter reason:",
        "cannot_create": "Cannot create",
        "check": "Validation",
        "ok": "OK",
        "rejected": "Rejected",
        "database_rows": "Database rows",
        "files": "Files",
        "warnings": "Warnings",
        "errors": "Errors",
        "no": "none",
        "provider_page_note": "AI and CLI: installation, authentication, access and readiness are checked separately. Installation and login are not started automatically in this phase.",
        "repeat_check": "Check again",
        "diagnostics": "Diagnostics",
        "roles_readonly": "Role creation and editing are planned for the next phase. Roles are currently available for viewing and assignment.",
        "responsibilities": "Role responsibilities",
        "restrictions": "Restrictions",
        "direct_grants": "Additional permissions",
        "direct_denies": "Denied permissions",
        "effective_permissions": "Effective permissions",
        "identity": "Profile",
        "organization": "Organization",
        "professions": "Professions",
        "skills": "Skills",
        "learning": "Learning",
        "templates": "Templates",
        "settings": "Settings",
        "configuration_health": "Configuration health",
        "execution_eligibility": "Execution eligibility",
        "employee": "Employee",
        "provider_id": "Provider ID",
        "display_name": "Display name",
        "family": "Family",
        "adapter": "Adapter",
        "executables": "Executables",
        "install_strategy": "Install strategy",
        "auth_strategy": "Auth strategy",
        "required_capabilities": "Required capabilities",
        "limitations": "Limitations",
        "last_health": "Last health",
        "install": "Install",
        "auth": "Auth",
        "access": "Access",
        "health": "Health",
        "capabilities": "Capabilities",
        "version": "Version",
        "action": "Action",
        "object_type": "Object type",
        "object_id": "Object ID",
        "previous": "Previous",
        "new": "New",
        "time": "Time",
        "actor": "Actor",
        "filter_audit": "Filter by action, object or employee",
        "not_saved": "Not saved",
        "check_data": "Check data",
        "name_required": "Employee name is required.",
        "agent_id_required": "Employee ID must start with agent-.",
        "role_required": "Select at least one role.",
        "permissions_note": "Additional permissions. Owner permissions are not assigned in this window.",
        "change_reason": "Change reason:",
        "foreign_key_error": "Could not save: selected role or provider is not registered. Refresh the window and try again.",
        "unknown_role": "Unknown role",
        "unknown_provider": "Unknown provider",
        "unknown_agent": "Employee not found",
        "empty_display_name": "Employee name is empty",
    },
}


ROLE_LABELS = {
    "ru": {
        "PROJECT_MANAGER": "Руководитель проекта",
        "DESIGN_ENGINEER": "Инженер-проектировщик",
        "QA_ENGINEER": "Инженер ОТК",
        "VERIFICATION_ENGINEER": "Инженер проверки",
        "DOCUMENT_CONTROL_OFFICER": "Специалист по документации",
        "LEARNING_COORDINATOR": "Координатор обучения",
        "RESEARCH_ASSISTANT": "Исследователь",
        "CUSTOM_ROLE": "Другая роль",
    },
    "uk": {
        "PROJECT_MANAGER": "Керівник проєкту",
        "DESIGN_ENGINEER": "Інженер-проєктувальник",
        "QA_ENGINEER": "Інженер ВТК",
        "VERIFICATION_ENGINEER": "Інженер перевірки",
        "DOCUMENT_CONTROL_OFFICER": "Спеціаліст з документації",
        "LEARNING_COORDINATOR": "Координатор навчання",
        "RESEARCH_ASSISTANT": "Дослідник",
        "CUSTOM_ROLE": "Інша роль",
    },
    "en": {
        "PROJECT_MANAGER": "Project Manager",
        "DESIGN_ENGINEER": "Design Engineer",
        "QA_ENGINEER": "Quality Engineer",
        "VERIFICATION_ENGINEER": "Verification Engineer",
        "DOCUMENT_CONTROL_OFFICER": "Documentation Specialist",
        "LEARNING_COORDINATOR": "Learning Coordinator",
        "RESEARCH_ASSISTANT": "Researcher",
        "CUSTOM_ROLE": "Custom role",
    },
}


STATUS_LABELS_I18N = {
    "ru": {"DRAFT": "Черновик", "ACTIVE": "Активен", "SUSPENDED": "Приостановлен", "DISABLED": "Отключен", "ARCHIVED": "Архив"},
    "uk": {"DRAFT": "Чернетка", "ACTIVE": "Активний", "SUSPENDED": "Призупинений", "DISABLED": "Вимкнений", "ARCHIVED": "Архів"},
    "en": {"DRAFT": "Draft", "ACTIVE": "Active", "SUSPENDED": "Suspended", "DISABLED": "Disabled", "ARCHIVED": "Archived"},
}


WORKFLOW_LABELS_I18N = {
    "ru": {
        "ASSIGNED": "Назначен",
        "STUDYING": "Изучается",
        "PRACTICED": "Отработан",
        "DEMONSTRATED": "Подтверждён работой",
        "REVIEWED": "Проверен",
        "REQUIRES_RETRAINING": "Нужно переобучение",
        "NEEDS_REVIEW": "Нужна проверка",
        "REJECTED": "Отклонено",
        "SUSPENDED": "Приостановлено",
        "IN_REWORK": "На доработке",
        "READY_FOR_RECHECK": "Готово к перепроверке",
        "RESOLVED": "Исправлено",
        "ACCEPTED_RISK": "Риск принят",
        "DRAFT": "Черновик",
        "ACTIVE": "Активно",
    },
    "uk": {
        "ASSIGNED": "Призначено",
        "STUDYING": "Вивчається",
        "PRACTICED": "Відпрацьовано",
        "DEMONSTRATED": "Підтверджено роботою",
        "REVIEWED": "Перевірено",
        "REQUIRES_RETRAINING": "Потрібне перенавчання",
        "NEEDS_REVIEW": "Потрібна перевірка",
        "REJECTED": "Відхилено",
        "SUSPENDED": "Призупинено",
        "IN_REWORK": "На доопрацюванні",
        "READY_FOR_RECHECK": "Готово до повторної перевірки",
        "RESOLVED": "Виправлено",
        "ACCEPTED_RISK": "Ризик прийнято",
        "DRAFT": "Чернетка",
        "ACTIVE": "Активно",
    },
    "en": {
        "ASSIGNED": "Assigned",
        "STUDYING": "Studying",
        "PRACTICED": "Practiced",
        "DEMONSTRATED": "Demonstrated in work",
        "REVIEWED": "Reviewed",
        "REQUIRES_RETRAINING": "Retraining required",
        "NEEDS_REVIEW": "Needs review",
        "REJECTED": "Rejected",
        "SUSPENDED": "Suspended",
        "IN_REWORK": "In rework",
        "READY_FOR_RECHECK": "Ready for recheck",
        "RESOLVED": "Resolved",
        "ACCEPTED_RISK": "Risk accepted",
        "DRAFT": "Draft",
        "ACTIVE": "Active",
    },
}


READINESS_LABELS = {
    "ru": {
        "READY": "Готов к работе",
        "DEGRADED": "Работает с ограничениями",
        "AUTHENTICATION_REQUIRED": "Нужна авторизация",
        "PROVIDER_NOT_INSTALLED": "CLI не установлен",
        "PROVIDER_NOT_ASSIGNED": "Провайдер не назначен",
        "ACCESS_CHECK_REQUIRED": "Нужна проверка доступа",
        "CAPABILITY_TEST_REQUIRED": "Нужна проверка возможностей",
        "PLAN_INCOMPATIBLE": "Нет подходящего доступа",
        "BLOCKED": "Заблокирован",
        "PROFILE_INCOMPLETE": "Профиль неполный",
        "SETUP_FAILED": "Настройка не удалась",
    },
    "uk": {
        "READY": "Готовий до роботи",
        "DEGRADED": "Працює з обмеженнями",
        "AUTHENTICATION_REQUIRED": "Потрібна авторизація",
        "PROVIDER_NOT_INSTALLED": "CLI не встановлено",
        "PROVIDER_NOT_ASSIGNED": "Провайдер не призначено",
        "ACCESS_CHECK_REQUIRED": "Потрібна перевірка доступу",
        "CAPABILITY_TEST_REQUIRED": "Потрібна перевірка можливостей",
        "PLAN_INCOMPATIBLE": "Немає відповідного доступу",
        "BLOCKED": "Заблоковано",
        "PROFILE_INCOMPLETE": "Профіль неповний",
        "SETUP_FAILED": "Налаштування не вдалося",
    },
    "en": {
        "READY": "Ready",
        "DEGRADED": "Limited operation",
        "AUTHENTICATION_REQUIRED": "Authentication required",
        "PROVIDER_NOT_INSTALLED": "CLI is not installed",
        "PROVIDER_NOT_ASSIGNED": "Provider is not assigned",
        "ACCESS_CHECK_REQUIRED": "Access check required",
        "CAPABILITY_TEST_REQUIRED": "Capability check required",
        "PLAN_INCOMPATIBLE": "Required access is unavailable",
        "BLOCKED": "Blocked",
        "PROFILE_INCOMPLETE": "Profile is incomplete",
        "SETUP_FAILED": "Setup failed",
    },
}


PERMISSION_LABELS = {
    "ru": {
        "CHAT": "Общаться в чате",
        "READ_WORKSPACE": "Читать рабочую папку",
        "WRITE_WORKSPACE": "Создавать и менять файлы",
        "DELETE_FILES": "Удалять файлы",
        "RUN_COMMANDS": "Запускать команды",
        "MODIFY_PROJECT": "Менять проект",
        "CREATE_DOCUMENTS": "Создавать документы",
        "REVIEW_ARTIFACTS": "Проверять результаты",
        "CREATE_FINDINGS": "Создавать замечания ОТК",
        "CLOSE_FINDINGS": "Закрывать замечания ОТК",
        "MANAGE_SKILLS": "Управлять скиллами",
        "MANAGE_KNOWLEDGE": "Управлять знаниями",
        "MANAGE_EMPLOYEES": "Управлять сотрудниками",
        "MANAGE_STANDARDS": "Управлять стандартами",
        "REQUEST_APPROVAL": "Запрашивать согласование",
        "GRANT_APPROVAL": "Выдавать согласование",
        "ACCESS_INTERNET": "Искать в интернете",
        "ACCESS_EXTERNAL_PATHS": "Доступ вне рабочей папки",
    },
    "uk": {
        "CHAT": "Спілкуватися в чаті",
        "READ_WORKSPACE": "Читати робочу папку",
        "WRITE_WORKSPACE": "Створювати і змінювати файли",
        "DELETE_FILES": "Видаляти файли",
        "RUN_COMMANDS": "Запускати команди",
        "MODIFY_PROJECT": "Змінювати проєкт",
        "CREATE_DOCUMENTS": "Створювати документи",
        "REVIEW_ARTIFACTS": "Перевіряти результати",
        "CREATE_FINDINGS": "Створювати зауваження ВТК",
        "CLOSE_FINDINGS": "Закривати зауваження ВТК",
        "MANAGE_SKILLS": "Керувати скілами",
        "MANAGE_KNOWLEDGE": "Керувати знаннями",
        "MANAGE_EMPLOYEES": "Керувати співробітниками",
        "MANAGE_STANDARDS": "Керувати стандартами",
        "REQUEST_APPROVAL": "Запитувати погодження",
        "GRANT_APPROVAL": "Видавати погодження",
        "ACCESS_INTERNET": "Шукати в інтернеті",
        "ACCESS_EXTERNAL_PATHS": "Доступ поза робочою папкою",
    },
    "en": {
        "CHAT": "Chat",
        "READ_WORKSPACE": "Read workspace",
        "WRITE_WORKSPACE": "Create and edit files",
        "DELETE_FILES": "Delete files",
        "RUN_COMMANDS": "Run commands",
        "MODIFY_PROJECT": "Modify project",
        "CREATE_DOCUMENTS": "Create documents",
        "REVIEW_ARTIFACTS": "Review results",
        "CREATE_FINDINGS": "Create findings",
        "CLOSE_FINDINGS": "Close findings",
        "MANAGE_SKILLS": "Manage skills",
        "MANAGE_KNOWLEDGE": "Manage knowledge",
        "MANAGE_EMPLOYEES": "Manage employees",
        "MANAGE_STANDARDS": "Manage standards",
        "REQUEST_APPROVAL": "Request approval",
        "GRANT_APPROVAL": "Grant approval",
        "ACCESS_INTERNET": "Search the internet",
        "ACCESS_EXTERNAL_PATHS": "Access outside workspace",
    },
}


def normalize_language(language: str | None) -> str:
    return language if language in SUPPORTED_LANGUAGES else "ru"


def tr(language: str, key: str) -> str:
    language = normalize_language(language)
    return TEXT.get(language, TEXT["ru"]).get(key, TEXT["ru"].get(key, key))


def role_label(language: str, role_id: str) -> str:
    language = normalize_language(language)
    return ROLE_LABELS.get(language, {}).get(role_id, role_id.replace("_", " ").title())


def status_label(language: str, status: str) -> str:
    language = normalize_language(language)
    labels = STATUS_LABELS_I18N.get(language, {})
    return labels.get(status, WORKFLOW_LABELS_I18N.get(language, {}).get(status, status))


def workflow_label(language: str, value: str) -> str:
    language = normalize_language(language)
    return WORKFLOW_LABELS_I18N.get(language, {}).get(value, value.replace("_", " ").title())


def readiness_label(language: str, readiness: str) -> str:
    language = normalize_language(language)
    return READINESS_LABELS.get(language, {}).get(readiness, readiness.replace("_", " ").title())


def permission_label(language: str, permission: str) -> str:
    language = normalize_language(language)
    return PERMISSION_LABELS.get(language, {}).get(permission, permission.replace("_", " ").title())
