from __future__ import annotations

from typing import Any, Protocol

from .models import AgentAction, AgentResult, TraceEvent, WorkflowDefinition, WorkflowState


class WorkflowEngine(Protocol):
    def create_workflow(self, organization_id: str, goal: str, definition: WorkflowDefinition) -> WorkflowState: ...
    def start(self, workflow_id: str) -> WorkflowState: ...
    def pause(self, workflow_id: str) -> WorkflowState: ...
    def resume(self, workflow_id: str) -> WorkflowState: ...
    def cancel(self, workflow_id: str) -> WorkflowState: ...
    def checkpoint(self, workflow_id: str) -> WorkflowState: ...
    def get_state(self, workflow_id: str) -> WorkflowState: ...
    def submit_human_decision(self, workflow_id: str, step_id: str, approved: bool) -> WorkflowState: ...


class AgentRuntime(Protocol):
    def execute(self, action: AgentAction, provider_id: str) -> AgentResult: ...


class ProviderAdapter(Protocol):
    provider_id: str

    def capabilities(self) -> set[str]: ...
    def execute(self, action: AgentAction) -> AgentResult: ...


class CheckpointStore(Protocol):
    def save(self, state: WorkflowState) -> None: ...
    def load(self, workflow_id: str) -> WorkflowState: ...
    def exists(self, workflow_id: str) -> bool: ...


class TraceService(Protocol):
    def emit(self, event: TraceEvent) -> None: ...
    def list_events(self, workflow_id: str) -> list[TraceEvent]: ...


class ArtifactRegistry(Protocol):
    def add_revision(self, state: WorkflowState, artifact_data: dict[str, Any], *, employee_id: str, provider_id: str) -> str: ...


class FindingRegistry(Protocol):
    def add(self, state: WorkflowState, finding_data: dict[str, Any]) -> str: ...
    def transition(self, state: WorkflowState, finding_id: str, status: str) -> None: ...
